f--
fitle: " Weekly Staff Schdule Optimization Model V2"
author: "Shuai Wang, Eugene Pyatigorsky"
date: "8/17/2019"
output: html_document
--


## Notes:
Backgroud: a dog care(opens 24/7) with 4 locations needs a staff scheduling system. 
The employee are able to work at all 4 location with preference, and they have 
hard constraint on the shifts(ex, students cannot work on day shift, artists
cannot work on night shift). Multi-sills are also considered. 

This V2 model contains weekly shift, multilocation preference, skill preference,
shift availability for employee.

# Sets:
|  Name         | Index        | Comments      |       
|---------------|--------------|-------        |
1. **Employee** | e | employee1-1000           |
2. **Locations**| l | locations1-4             |
3. **Shift**    | sh| predefined full shift like 6-14, partial shift 6:30-10:30|
4. **Skills**   | sk| skill1-4                 |
5. **Day**      | d | days of the week. 1-8    |
6. **Hour**     | h | 1-24 hour                |
7. **ShiftBlock**| b | data: {day, afternoon, night}|



## Parameters:

### Demand:
1. **$Demand_{l,d,sk,h}$**: 
Skill breakdown requirment in labor hours(**or #labor if it's too granular **)

### Shift
1. **$ShiftLen_{l,sh}$**: Shift length in hours 

2. **$ShiftHourMap_{l, sh, h}$**: 0-1 matrix. Shift maps to location and hour

3. **$ShiftTimeBlockMap_{sh}$**: the time block of the shift 
 
### Employee
 
 1. **$EmployeeShiftMap_{e,d,sh}$**: binary. employee availaibility for shift sh on day d.                           
                                                                                 
 2. **$EmployeeLocPref_{e,l}$**: {-2,-1,0,1} negtive meaning not prefer 
                                                                                 
 3. **$EmployeeSkillMap_{e,sk}$**: binary  employee and skill mapping      
 
 4. **$EmployeeMax/MinHour_{e}$**: max/min hours per week of for each employee      
 
 5. **$EmployeeCost_{e}$**: cost of each employee               
 
             
 
## Variable:                                                                     
 1. **$Assign_{e,l, d, sh, sk}$**: binary. If assign the shift to employee or not 
 
 2. **$Uncover_{e,l,d,sh,sk}$**: nonnegetive. uncovered demand/gap for shift **not used**
 
## Objective:
**EmployeeCost**: 

$$\sum_{e}\sum_{l}\sum_{d}\sum_{sh}\sum_{sk}Assign_{e,l,d,sk,sh} *EmployeeCost_{e}$$

**Penalty**

1. LocaPrefPenalty:
$$LocPenality * \sum_{e}\sum_{l}\sum_{d}\sum_{sh}\sum_{sk}
  Assign_{e,l,d,sk,sh}*EmployeeLocPref_{e,l}$$

**Minimize**  
 $$  \text{EmployeeCost + LocPrefPenalty}$$  
 
 
## Constraints:
1. Only one shift is allowed:

employee e, on day d, location l, and shift l can be only asssigned to 1.     

$$\sum_{l}\sum_{sh}\sum_{sk} Assign_{e,l,d,sk,sh} \leq 1, \forall  \text{ e, d}$$

2. Satisfy demand :

2.1 $$\sum_{e}\sum_{sh} Assign_{e,l,d,sk,sh} * ShiftHourMap_{l, sh, h}  \geq Demand_{l,d,sk,h},  \forall  \text{ l, d, sk, h}$$
2.2 overnight shift meets the demand

$$Assign_{e,l,d-1, sk, sh = Overnight} * ShiftHourMap_{l, sh = Overnight, h} $$

3. Assignment Satisfies Shift:
If the employee's is available for a shift, then he/she can be assigned.

$$\sum_{l}\sum_{sk} Assign_{e,l,d,sk,sh} \leq EmployeeShiftMap_{e,d,sh},  \forall  \text{ e, d, sh}$$

4. Assignment Satisfies skills:
If the emplpoyee has he needed skill for a position, then he/she can be assigned.

$$ Assign_{e,l,d,sk,sh} \leq EmployeeSkillMap_{e,sk},  \forall  \text{ e, l, d, sh, sk}$$


5. Employee's weekly hour limit:
$$\sum_{l}\sum_{d}\sum_{sh}\sum_{sk} Assign_{e,l,d,sk,sh} * ShiftLen_{l,sh} \leq EmployeeMaxHour_e, \forall  
\text{ e}$$


## optional constraints:

6. No day shift afte a night shift



$$  Assign_{e,l,d,sk,sh \in ShiftTimeBlockMap =night } +  Assign_{e,l,d+1,sk,sh \in  ShiftTimeBlockMap = day} <=1     \forall e, l, d-1, sk, sh $$

  
